import type { ApprovedSource } from "./types";

/** Stage approval supplied by the project owner; not a scholarly endorsement. */
export const approvedSources: readonly ApprovedSource[] = Object.freeze([
  { id: "hadeethenc-ar", title: "موسوعة الأحاديث النبوية – HadeethEnc", category: "SCHOLARLY_REFERENCE", canonicalUrl: "https://hadeethenc.com/ar/home", language: "ar", edition: "Live Arabic official API; version not supplied", licenseNotes: "Official API documentation and reuse terms linked from https://hadeethenc.com/en/home. Retain original text and clear attribution; update any retained copy when source data changes.", approvedBy: "Project owner — approved hadith explanation request", approvedAt: "2026-10-06", scopeNotes: "Approved explanation/reference support via documented search and Arabic detail API. Deterministic matn matching only; not LLM-generated evidence. No local bulk index or inferred public record URLs." },
  { id: "quranpedia-hafs", title: "Quranpedia — Hafs Quran", category: "QURAN", canonicalUrl: "https://quranpedia.net", language: "ar", edition: "API mushaf 1 (Hafs)", licenseNotes: "Live API use: https://quranpedia.net/api-docs. No bulk download or republished dump.", approvedBy: "Project owner — evidence retrieval stage request", approvedAt: "2026-10-05", scopeNotes: "Read-only verse lookups and bounded topic discovery; no claim verdicts." },
  { id: "quranpedia-tafsir-1", title: "Quranpedia — تيسير التفسير", category: "TAFSIR", canonicalUrl: "https://quranpedia.net/book/1", language: "ar", edition: "API book 1; edition reported per response, unknown when absent", licenseNotes: "Live API use: https://quranpedia.net/api-docs. Original markup retained, display text derived without AI.", approvedBy: "Project owner — evidence retrieval stage request", approvedAt: "2026-10-05", scopeNotes: "Context for explicitly cited Quran interpretations only; not a comprehensive tafsir search." },
  { id: "sahihayn-bukhari", title: "صحيح البخاري", category: "HADITH", canonicalUrl: "https://sunnah.com/bukhari", language: "ar", edition: "Edition not supplied; source reference identifiers retained", licenseNotes: "Index representation: meeAtif/hadith_datasets, pinned revision; MIT declared by dataset card. See data/hadith/README.md for provenance limits.", approvedBy: "Project owner — local Sahihayn stage request", approvedAt: "2026-10-05", scopeNotes: "7,277 local records, exact Arabic wording and supplied references. LOCAL_PRIMARY; not an LLM or dataset-host religious authority." },
  { id: "sahihayn-muslim", title: "صحيح مسلم", category: "HADITH", canonicalUrl: "https://sunnah.com/muslim", language: "ar", edition: "Edition not supplied; suffixes and grouped references retained", licenseNotes: "Index representation: meeAtif/hadith_datasets, pinned revision; MIT declared by dataset card. See data/hadith/README.md for provenance limits.", approvedBy: "Project owner — local Sahihayn stage request", approvedAt: "2026-10-05", scopeNotes: "7,368 local records, including narration variants. LOCAL_PRIMARY; no invented grading, narrator, or page metadata." },
  { id: "dorar-official-api", title: "Dorar — official Hadith Encyclopedia API", category: "HADITH", canonicalUrl: "https://dorar.net/hadith", language: "ar", edition: "Live official search response; book/reference only when supplied", licenseNotes: "Official API usage: https://dorar.net/article/389. No HTML page scraping or bulk corpus license asserted.", approvedBy: "Project owner — official Dorar API stage request", approvedAt: "2026-10-05", scopeNotes: "DORAR_CROSSCHECK: optional live search after a local Sahihayn miss. Local hits return immediately without Dorar. Reported grades are source metadata, not claim verdicts." },
]);
